# Generated by Django 3.2.14 on 2022-09-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('base_salary', models.IntegerField()),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.management')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateTimeField(auto_now=True, help_text='AAAA-MM-DD')),
                ('genre', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=20)),
                ('cuil', models.IntegerField(max_length=15)),
                ('dni', models.IntegerField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.management')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.puesto')),
            ],
        ),
    ]
