# Generated by Django 3.2.14 on 2022-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cuil',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
