# Generated by Django 3.2.14 on 2022-09-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220928_0719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Management',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='cuil',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dni',
            new_name='tax_id_number',
        ),
        migrations.RenameField(
            model_name='puesto',
            old_name='management',
            new_name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='Argentina', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(auto_now=True, help_text='AAAA-MM-DD'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='base_salary',
            field=models.FloatField(),
        ),
    ]
