# Generated by Django 3.2.14 on 2022-10-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='img/no-image.png', upload_to='profile_images'),
        ),
    ]
