# Generated by Django 3.2.14 on 2022-10-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20220930_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='genre',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], default='FEMENINO', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(default='na', on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(),
        ),
    ]
