# Generated by Django 3.2.14 on 2022-10-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departamento'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado'},
        ),
    ]
