# Generated by Django 3.2.14 on 2022-11-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_merge_0004_auto_20221030_1735_0007_message_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('date', models.DateField()),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_sal', to='employee.employee')),
            ],
        ),
    ]
