# Generated by Django 3.2.14 on 2022-11-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20221030_1735'),
        ('employee', '0008_alter_employee_address'),
    ]

    operations = [
    ]
