# Generated by Django 4.0.5 on 2022-11-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_merge_0004_auto_20221028_1240_0004_auto_20221030_1735'),
        ('employee', '0009_merge_20221108_1439'),
    ]

    operations = [
    ]
