# Generated by Django 4.0.5 on 2022-11-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_merge_20221108_1833'),
        ('employee', '0010_overtime'),
    ]

    operations = [
    ]
