# Generated by Django 3.2.14 on 2022-11-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_address'),
        ('employee', '0010_overtime'),
    ]

    operations = [
    ]
