# Generated by Django 3.2.14 on 2022-10-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='no-image.png', upload_to='profile_images/'),
        ),
    ]
